### ISSUE TITLE
only commpass

### ISSUE THREAD

**Issue by mugdad1** [AkaneFoundation/Omni#4]
![Screenshot_20240529_090050_Omni.jpg](https://github.com/AkaneFoundation/Omni/assets/128133561/a97da62f-dda1-4fc0-bdc2-e8256086ebe9)

**Comment by AkaneTan** [comment]
Yes as I'm busy with my tests in the next week so expect more features to roll out in the future. :)

**Comment by mugdad1** [comment]
ok
