### ISSUE TITLE
No button to change tool

### ISSUE THREAD

**Issue by RemyBorius** [AkaneFoundation/Omni#5]
Really cool and beautiful app !

On my device, the button on the bottom right (that I can see on fdroid screenshots) is not displayed, and I can't change tool

My phone is a samsung S10e (Snapdragon), on custom rom DotOS (android 11)

**Comment by ThatOneCalculator** [comment]
I can't change the tool either, Pixel 7 on Android 14

**Comment by YodelPenguin** [comment]
I can mirror this issue too, Motorola Edge 40 on Android 14.

**Comment by Golem642** [comment]
That is because those are a work in progress, they are shown on the screenshot and probably partially implemented on a beta build of the app that the developer keeps for themselves for now, or the screenshots are just designs to preview the future tools

**Comment by needsMoreTurbo** [comment]
Adding another user to the list of people with this issue, running Pixel 7 Pro, Android 14. 

I really like the aesthetics of the app, just wish all of the features were functional.

**Comment by j-lakeman** [comment]
See https://github.com/AkaneFoundation/Omni/issues/4#issuecomment-2136744325

**Comment by nift4** [comment]
added
